language: c

# See http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env: COMPILER=gcc-4.9 COVERAGE=ON
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang-3.8

install:
  - pip install --user urllib3[secure]
  - pip install --user cpp-coveralls

script:
  - cmake -DCMAKE_C_FLAGS='-Wall -Wextra -Werror -coverage' -DCMAKE_BUILD_TYPE=Release .
  - make -j
  - make test

after_success:
  - test "${COVERAGE}" == 'ON' && coveralls --gcov-options '\-lp' --gcov 'gcov-4.9'
